### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by polikin** [wessman/defer.js#2]
Hey, 

I don't exactly how to use defer.js.

Ex: I want to load this js (`<script src="http://foo.com/static//libs/responsive-nav.min.js?v=11" type="text/javascript"></script>`). How can I do it with defer.js?

**Comment by wessman** [comment]
defer.js has some loading facilities, but they’re the same as loading the JavaScript file via HTML; the code simply adds the script tag to the DOM.

If defer.js is already loaded, you can use: `window.defer.appendScript( "http://foo.com/static//libs/responsive-nav.min.js?v=11"  , “async” );`. Note that this is the same as `<script src="http://foo.com/static//libs/responsive-nav.min.js?v=11" type="text/javascript” async></script>`

This last line of HTML is how you should really load your JS, with or without defer.js. If the JS in your external file requires nothing, then you don’t even need this library. If, on the other hand, your code _requires_ something, like jQuery or any other code to load first, then defer.js can help.

First, add the script tags to your page: 

```
<script src="http://foo.com/static//libs/defer.js" type="text/javascript” async></script>
<script src="http://foo.com/static//libs/responsive-nav.min.js?v=11" type="text/javascript” async></script>
```

Then, _within your JS file_, add code to the top and bottom like so:

```
window.defer = window.defer || [];
window.defer.push(
    p:function(){ !!window.jQuery },
    h:function(){
        //your code here!
    },
    o:{}
);
```

This way, the code in your other file will never execute before any code it needs gets loaded, it’s safe! You get all the benefits of the fast async loading modern browsers offer, without having things load out of order. No library will load code faster than an async-capable browser, the question is whether the code that gets loaded can handle arriving at the browser in any old order. That safety is what defer.js really offers.

Hope that helps!

**Comment by polikin** [comment]
Thanks!
